### ISSUE TITLE
Issue with `setPushRegistrationToken` - token seems to be transformed

### ISSUE THREAD

**Issue by sslash** [freshworks/freshchat-ios#117]
We are having an issue with registering push notification tokens on ios, through React native. 
The problem seems to be with the token that is saved when we call `Freshchat.setPushRegistrationToken(pushToken)`. The token we have on the javascript side is a valid token, but on the native side, its a different and presumably invalid token. 
We've proved that the token we have on JS is correct, by sending a push notification to that token. However, when we try to trigger a push notification by creating chat messages in Freshchat to our phone, while the phone is locked, no push notification is received. 
Looking at the Freshchat push notification debug-website, we do indeed get an APNS badTokenError.

We have uploaded both dev and prod APNS certificates to Freshchat. After debugging a bit we've found that the apns token that is sent from the native side, is not the same as the one we pass down from javascript. Here's a copy of our log when we call `Freshchat.setPushRegistrationToken(pushToken)`:
```
2020-08-16 08:48:39.752811+0200 lift[10432:5095934] [javascript] Registring token in JS: fpQlh2l-U8s:APA91bHaMZxkrZofbx1BEkUye1khJcSFgvowtsfLmC7nGyiYrEpKHCSFmC3uF7y_egWD9zPbR5BCm5MWyojOkj7qjuHf-hRCk-IPCfyE6YW9WWSlru8ShJQgS8w8mVFV4ZBbucHLxdWH
2020-08-16 08:48:39.900798+0200 lift[10432:5095941] FRESHCHAT: Push token registered : 0f00000000000aa91b00000000000b1b0e00e10000000000000f00070000000000000003f7000e00090000bc000000000007000000000000cf0006000000000800000000000f04bb00000000
```

Note how those two tokens are different. The first one is the one we've successfully manually triggered a push message to. 

Any help would be highly appreciated!

**Comment by hemanth-sudarsan** [comment]
@sslash Can you please send the notification debug result you got. Also passing token from both native and react native it will work. The difference here is in react native the library you use for push notification will convert data to string, whereas in native side you are getting the raw data (both should work in Freshchat SDK). Also confirm whether you are checking in debug app build with debug certificate uploaded and vice versa for prod. If this step is wrong then that also results in badTokenError.

**Comment by sslash** [comment]
Here's the debug log: https://web.freshchat.com/app/api/notif_debug?convId=388322550961908
> Also confirm whether you are checking in debug app build with debug certificate
I'm running the app in debug mode on my phone. I've uploaded both prod and sandbox certificates to Freshchat (checking the production certificate box to `on` for the prod certificate). How do I know whether freshchat use the sandbox and not production certificate when I run the app in debug mode?

**Comment by hemanth-sudarsan** [comment]
@sslash We dont have access to your account. Please attach the log results you got in the support ticket you have raised, which will be very helpful for further debugging.

**Comment by sslash** [comment]
My mistake, here's the output:
```
{"user":{"firstName":"Signaling Bus","id":388322549769449,"alias":"DBA840ED-2771-4B88-9877-EA3D285B96AB","groupAliasSet":[],"usage_meta":[],"kv_meta":[],"device_meta":[],"notificationId":"0f00000000000aa91b00000000000b1b0e00e10000000000000f00070000000000000003f7000e00090000bc000000000007000000000000cf0006000000000800000000000f04bb00000000","notificationType":2,"createdMillis":1597560510003,"updatedMillis":1597560519849,"type":0,"clientVersionCode":0,"clientType":0,"appId":0,"roleId":0,"experienceGroupId":0,"totalSessions":0,"deleted":0,"profilePicUrl":"https://s3.amazonaws.com/fresh-chat-names/img/bus.png","freshIdActivated":false,"lastSeenMillis":0,"present":false,"isNameGenerated":true,"usePriorityInbox":false,"activeForBillingCycle":false,"manuallyDeactivated":false,"dormantAgent":false,"liveTranslateEnabled":false,"isShadowBanned":false,"hardDeleted":false,"markedForDeletion":false,"isRbacForbidden":false,"jwtAuthStatus":0,"unsubscribedFromCampaign":false,"preview":false},"pushSuccessOnServer":true,"pushEnabled":true,"apnsPushResult":{"cert":{"certId":321,"certName":"Certificates.p12","production":0,"password":"****","appId":276192387840130,"bundleId":"com.liftandcast.liftandcast"},"deliveryError":"BadDeviceToken","apnsMessage":"SimpleApnsPushNotification [token=0f00000000000aa91b00000000000b1b0e00e10000000000000f00070000000000000003f7000e00090000bc000000000007000000000000cf0006000000000800000000000f04bb00000000, payload={\"aps\":{\"badge\":1,\"alert\":{\"body\":\"{\\\"source\\\":\\\"freshchat_user\\\"}\"},\"sound\":\"default\"}}, invalidationTime=Tue Aug 18 00:00:00 UTC 2020, priority=IMMEDIATE, topic=com.liftandcast.liftandcast, apns-collapse-id=null]","exceptionMessage":""}}
```

**Comment by hemanth-sudarsan** [comment]
@sslash Can you please let me know what version of React native Freshchat SDK is being used?

**Comment by sslash** [comment]
react-native-freshchat-sdk@2.6.2

**Comment by hemanth-sudarsan** [comment]
@sslash 
2020-08-17 17:41:53.121092+0530 oldfirebase[2440:737271] [javascript] 'Your APNS Token is:', '2A8DE8938D6E9F10EA2FBD819ADD304C237518A80338CA962C189085BF613794'
2020-08-17 17:42:17.906011+0530 oldfirebase[2440:737572] FRESHCHAT: Push token registered : 2a8de8938d6e9f10ea2fbd819add304c237518a80338ca962c189085bf613794
I tried in my sample project its working as expected.
And from the push token you shared it seems not a valid token(A valid token will be of length 64). I will attach some sample projects here for your reference. You can check those and implement the same.

1. Native implementation.
2. New firebase plugin RNFirebase >v6.x.x
3. Old firebase plugin RNFirebase <=v5.x.x
	
	**Running the project details to be shared to customer:**
1. Do NPM install first.
2. DO pod install in ios folder.
3. Add your app id and app key in index.js.
4. Add your bundle identifier in the project settings.

[nativeimplemantation.zip](https://github.com/freshdesk/freshchat-ios/files/5084122/nativeimplemantation.zip)
[newfirebase.zip](https://github.com/freshdesk/freshchat-ios/files/5084123/newfirebase.zip)
[oldfirebase.zip](https://github.com/freshdesk/freshchat-ios/files/5084124/oldfirebase.zip)

**Comment by hemanth-sudarsan** [comment]
@sslash Is this one resolved?

**Comment by sslash** [comment]
@hemanth-sudarsan I just ran the newfirebase project, and it works great! I noticed you never call `setPushRegistrationToken`, even though push handling works as it should. Whats the reason for that? The docs seem to state clearly that in order to have push notifications you must call this function. I might be misunderstanding of course 😬

**Comment by hemanth-sudarsan** [comment]
@sslash I put the calls inside Appdelegate.m file (Handling all push notifications codes natively). Please have a look into the file.
