### ISSUE TITLE
Function to check if the conversation already being shown to prefer multiple instance.

### ISSUE THREAD

**Issue by thidayatullah** [freshworks/freshchat-ios#118]
I have a case when a `showMessage()` function called multiple times, and it causes a multiple layer of chat screen being presented.
It would be great if there's a function / notification we can observe to check if the chat screen is currently being presented or already closed.

For example with Intercom SDK there's `IntercomWindowDidShow` and `IntercomWindowDidHide` Notification we can observe.

**Comment by harish-kumarc** [comment]
HI @thidayatullah , you can listen to FreshchatSDK events to achieve it. The two events 1. "FCEventChannelListOpen" (for topics /channels list view) and 2. "FCEventConversationOpen"(when topic/channel message view opens) can be used for your use case. Please find more in events documentation [here](https://support.freshchat.com/support/solutions/articles/50000000057-how-to-track-user-actions-happening-inside-freshchat-sdk)

**Comment by thidayatullah** [comment]
Thanks @harish-kumarc !
