### ISSUE TITLE
International Compatibility

### ISSUE THREAD

**Issue by pendakill** [freshworks/freshchat-ios#119]
When it comes to internationalization, it is found that no matter what form of Chinese is, it can only be recognized and read zh.lporj , unable to distinguish traditional Chinese from simplified Chinese！！！

**Comment by deep-pradhan-fw** [comment]
@pendakill, You will get the fix in our next release. Thanks.

**Comment by hemanth-sudarsan** [comment]
@pendakill Closing this issue, SDK v3.7.8 have this fix.
