### ISSUE TITLE
Adding custom icon image with custom theme .plist file with correct file path

### ISSUE THREAD

**Issue by alihanaktay** [freshworks/freshchat-ios#121]
Hello I've created custom theme file for our freshchat integration. I can change all the colors and the text styles but when I try to change icon images  I can't add them to the project. Probably I'm not giving correct path to the icon file. Can you help me about this.

**This is where images and theme plist file saved.**
![Screen Shot 2020-10-09 at 11 15 04](https://user-images.githubusercontent.com/4999796/95559677-d1cc7200-0a20-11eb-8517-fd333525386e.png)

**This is the path I give to the FreshchatTheme.plist file**
airGsm-ios/airGsm-ios/FreshchatThemeResources/freshchat_upload_icon

**SDK Version = 3.7.7**

**Xcode Version = 12.0.1**

**Comment by hemanth-sudarsan** [comment]
@alihanaktay 
You can just mention the image name alone in your case.

**Comment by alihanaktay** [comment]
You mean like below right if so I've tried before it's still not working :( 

![Screen Shot 2020-10-13 at 15 22 35](https://user-images.githubusercontent.com/4999796/95859996-17ae7080-0d68-11eb-85a1-62efc8dd896f.png)

![Screen Shot 2020-10-13 at 15 22 43](https://user-images.githubusercontent.com/4999796/95860007-1bda8e00-0d68-11eb-816d-0cdfd7f2140c.png)

**Comment by hemanth-sudarsan** [comment]
@alihanaktay Once you have made the change in Theme file, clean the build and run it. 
Also make sure the images are included in Copy Bundle Resources under Build Phases.

**Comment by hemanth-sudarsan** [comment]
@alihanaktay Let me know if this is working at your end.

**Comment by hemanth-sudarsan** [comment]
@alihanaktay closing the issue. Reopen if it's not resolved.

**Comment by alihanaktay** [comment]
It's working perfectly thank you so much for your all help. @hemanth-sudarsan
