### ISSUE TITLE
Freshchat sent wrong user property and channel

### ISSUE THREAD

**Issue by Linkadi98** [freshworks/freshchat-ios#122]
Hello, 

I have an issue when sending user property and channel in fresh chat, sometimes freshchat can not send user property and channel therefore the messages of customer were redirected to wrong channel, almost times this issue doesn't happen but not 100%. I have set up freshchat following Freshchat doc but this issue still is a headache for me.

Could you provide some solutions for me to handle this issue?

Thanks

**Comment by harish-kumarc** [comment]
Hi @Linkadi98 ,
Need few clarification from your side. The issue you refers is user properties update(name, email, phone etc) and opening specific topic or channel based on tags provided?
Also wants to know if the messages aren't sent to correct topic, then are they going to default channel/topic? If so then the tags aren't matching with existing tags for topics and in that case messages will be sent default topics only.
Can you please share the implementation code snippet with us.

Thanks

**Comment by Linkadi98** [comment]
Hello, 

Thank you because of quick reply, I use a tag and a key to send user property to redirect freshchat user to a specific channel, when logins in app, if user is new one then I use `resetUser` api to clear the current user associated to the SDK, then use `setUserProperty(forKey:_, value:_)` api to redirect freshchat user to a channel with specific key and tag I defined.  In case login user doesn't change, then I don't use `resetUser` api. It's really weird that sometime user is redirected to default channel like you said before, but just sometime, not very often. Sorry I can not share implementation code because of my company's policy!

Thank you for your support

**Comment by harish-kumarc** [comment]
Hi @Linkadi98 got some gist from your explanation. Need one more info from your side, when you are redirected to default channel, what kind of users actually facing/experiencing this behaviour - new users or old users. As what I am suspecting is when resetuser API is called in that get topics is also there and within that we have tag values for topics. So if there is network delay then tags aren't added into SDK database and if showConversation is called in that case user will be redirected to default topic. One suggestion is you can try calling showConversation with tags within completion block of resetUser API. 
Thanks

**Comment by harish-kumarc** [comment]
Hi @Linkadi98, Let us know if are you able to resolve the issue.

**Comment by Linkadi98** [comment]
Hello, 

I have follow your suggestion and it works perfectly, thank you!
