### ISSUE TITLE
Carthage build error with Xcode 12.2

### ISSUE THREAD

**Issue by rafaelescoffier** [freshworks/freshchat-ios#123]
When building the latest Carthage version (v3.7.2), we are getting the following error:

`ld: in .../iOS/Carthage/Checkouts/freshchat-ios/FreshchatCarthage/FreshchatCarthage/libFDFreshchatSDK.a(FCViewController.o), building for iOS Simulator, but linking in object file built for iOS, file '.../iOS/Carthage/Checkouts/freshchat-ios/FreshchatCarthage/FreshchatCarthage/libFDFreshchatSDK.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

You can replicate this error by building the project for the Release build configuration using Xcode 12.

**Comment by billThePill** [comment]
Ditto. I am having a similar issue when attempting to build/run on iOS 14.2 Simulator (or 14.1 Simulator) on an Apple Silicon Mac. This does not occur when building for running on iOS 13.5 Simulator. If I build/run on the same simulators on an Intel Mac, I do not have the error. Building to an iPhone device running iOS 14.2 is not an issue either.

See a similar issue with Flutter: https://github.com/flutter/flutter/issues/64502

**Comment by harish-kumarc** [comment]
@billThePill thanks for the info. We will check and update.

**Comment by rafaelescoffier** [comment]
@harish-kumarc Any updates on this? Xcode 12 was released on September 16, 2020, not to mention all the betas before. And your SDK still doesn't fully support it. This is embarrassing to say the least.

**Comment by harish-kumarc** [comment]
Hi @rafaelescoffier , We have updated Carthage branch with solution of the above issue. Please check ```Note: Point 2``` before installation instructions [here](https://github.com/freshworks/freshchat-ios/tree/carthage)
