### ISSUE TITLE
Carthage version outdated

### ISSUE THREAD

**Issue by rafaelescoffier** [freshworks/freshchat-ios#124]
The latest release (4.0.1) was no added to the Carthage branch

**Comment by harish-kumarc** [comment]
Thanks @rafaelescoffier , we will update to latest version soon.

**Comment by rafaelescoffier** [comment]
Thanks @harish-kumarc

**Comment by harish-kumarc** [comment]
Hi @rafaelescoffier we have updated our Carthage branch. Please check [here](https://github.com/freshworks/freshchat-ios/tree/carthage)

**Comment by rafaelescoffier** [comment]
@harish-kumarc Thanks for the update
