### ISSUE TITLE
[Catalyst] Support For XC Framework

### ISSUE THREAD

**Issue by ilkerc** [freshworks/freshchat-ios#125]
Any roadmap on supporting catalyst builds? #102

**Comment by ilkerc** [comment]
@hemanth-sudarsan is this an active repository?

**Comment by hemanth-sudarsan** [comment]
@ilkerc We dont have any plans on doing this in near future. 
If anything urgent you can reach out to our product team.

**Comment by kientux** [comment]
Xcode 12.3 abandoned fat-binary framework, it enforces to use xcframework so we can no longer build our app with Freshchat dependency.

**Comment by hemanth-sudarsan** [comment]
#136 There is a beta release on SPM with XCFramework support.
Please use the PR and checkout the SDK.
If you are facing any issue, comment in the PR.
