### ISSUE TITLE
App crashing while set FCData

### ISSUE THREAD

**Issue by MuhammadBilal5674** [freshworks/freshchat-ios#129]
<img width="1062" alt="Screenshot 2021-01-05 at 5 10 27 PM" src="https://user-images.githubusercontent.com/73555616/103645250-87a05180-4f79-11eb-88a1-4e6326863a6e.png">

**Comment by MuhammadBilal5674** [comment]
Using sdk v(4.1.1)

**Comment by deep-pradhan-fw** [comment]
Hi @MuhammadBilal5674 .
Please help us with these information -
1. iOS Version 
2. Device/simulator model name?
3. Is the bug reproducible ? If yes, please share the steps.

Thanks.

**Comment by hemanth-sudarsan** [comment]
@MuhammadBilal5674 We could'nt reproduce this issue.
We will keep an eye on this issue. 
Closing this for now, feel free to open this if you could reproduce this again.
