### ISSUE TITLE
Getting errors in console for system blue color and factory registered id

### ISSUE THREAD

**Issue by miranhrupacki** [freshworks/freshchat-ios#131]
Hello, since I imported your Freshchat SDK and plist, I keep getting these errors in console:

2021-01-26 08:50:59.537836+0100 NameOfMyProject[7318:249413] color <UIDynamicSystemColor: 0x600002e23bc0; name = systemBlueColor>

and

2021-01-26 08:50:59.623563+0100 NameOfMyProject[7318:249413] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x600003baeaa0> F8BB1C28-BAE8-11D6-9C31-00039315CD46

What can I do to get rid of these errors? Or it's not problem from my side?
My app is not crashing due to these errors, but they keep showing in my console.
Thanks in advance, I am using Xcode: 12.3. and Swift 5.

**Comment by harish-kumarc** [comment]
Hi @miranhrupacki , systemXXXColor is added with Xcode 11 and iOS 13+, FreshchatSDK supports iOS 8+ so it is just a console log warning and shouldn't create any issue.

**Comment by miranhrupacki** [comment]
Ok, thanks @harish-kumarc. Do you know more about second error, factory id?

**Comment by harish-kumarc** [comment]
@miranhrupacki , Other warning doesn't look like via Freshchat, This [link](https://stackoverflow.com/questions/58360765/swift-5-1-error-plugin-addinstanceforfactory-no-factory-registered-for-id-c) can help you more to fix it.
