### ISSUE TITLE
 Exception: "*** -[NSBundle initWithURL:]: nil URL argument

### ISSUE THREAD

**Issue by vipulRajput** [freshworks/freshchat-ios#132]
I'm not able to initialise the Freshchat SDK, from the time I started integrating it:- 
|
|
let fchatConfig =  FreshchatConfig(appID: "x", andAppKey: "x")
fchatConfig.domain = "x.in.freshchat.com"
Freshchat.sharedInstance().initWith(fchatConfig)
|
|
|
|
you can check this for more info as well:- 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512539b2 objc_exception_throw + 48
	2   Foundation                          0x00007fff258b5ded +[NSBundle bundleWithURL:] + 0
	3   Foundation                          0x00007fff258b5e0e +[NSBundle bundleWithURL:] + 33
	4   Niyo Global                         0x0000000104305f74 -[FCTheme getHLResourceBundle] + 116
	5   Niyo Global                         0x0000000104305eb3 -[FCTheme getDefaultThemePath] + 24
	6   Niyo Global                         0x0000000104305e6e -[FCTheme getPathForTheme:] + 266
	7   Niyo Global                         0x0000000104305936 -[FCTheme setThemeWithName:] + 54
	8   Niyo Global                         0x0000000104306178 -[FCTheme fetchThemeValueForKey:] + 124
	9   Niyo Global                         0x00000001043086e6 -[FCTheme sdkFont] + 38
	10  Niyo Global                         0x0000000104305836 -[FCTheme init] + 100
	11  Niyo Global                         0x00000001043057b8 __25+[FCTheme sharedInstance]_block_invoke + 38
	12  libdispatch.dylib                   0x0000000109304e8e _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x00000001093063db _dispatch_once_callout + 66
	14  Niyo Global                         0x0000000104305790 +[FCTheme sharedInstance] + 97
	15  Niyo Global                         0x00000001043b1d95 __42-[Freshchat updateConfig:andRegisterUser:]_block_invoke + 1157
	16  libdispatch.dylib                   0x0000000109303f11 _dispatch_call_block_and_release + 12
	17  libdispatch.dylib                   0x0000000109304e8e _dispatch_client_callout + 8
	18  libdispatch.dylib                   0x000000010931656d _dispatch_root_queue_drain + 819
	19  libdispatch.dylib                   0x0000000109316ca6 _dispatch_worker_thread2 + 135
	20  libsystem_pthread.dylib             0x00007fff522b39f7 _pthread_wqthread + 220
	21  libsystem_pthread.dylib             0x00007fff522b2b77 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by vipulRajput** [comment]
for more info:-
Xcode version:- 11.6 
FreshChat SDK version:- 4.1.5
I'm running app in simulator.

**Comment by vipulRajput** [comment]
CoreData: error:  Cannot load NSManagedObjectModel.  nil is an illegal URL parameter

**Comment by vipulRajput** [comment]
[error] error:  Cannot load NSManagedObjectModel.  nil is an illegal URL parameter
CoreData: error:  Cannot load NSManagedObjectModel.  nil is an illegal URL parameter
2021-02-02 15:19:22.384584+0530 Niyo Global[24891:340916] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3de6e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff512539b2 objc_exception_throw + 48
	2   Foundation                          0x00007fff258b5ded +[NSBundle bundleWithURL:] + 0
	3   Foundation                          0x00007fff258b5e0e +[NSBundle bundleWithURL:] + 33
	4   Niyo Global                         0x00000001088b5f84 -[FCTheme getHLResourceBundle] + 116
	5   Niyo Global                         0x00000001088b5ec3 -[FCTheme getDefaultThemePath] + 24
	6   Niyo Global                         0x00000001088b5e7e -[FCTheme getPathForTheme:] + 266
	7   Niyo Global                         0x00000001088b5946 -[FCTheme setThemeWithName:] + 54
	8   Niyo Global                         0x00000001088b6188 -[FCTheme fetchThemeValueForKey:] + 124
	9   Niyo Global                         0x00000001088b86f6 -[FCTheme sdkFont] + 38
	10  Niyo Global                         0x00000001088b5846 -[FCTheme init] + 100
	11  Niyo Global                         0x00000001088b57c8 __25+[FCTheme sharedInstance]_block_invoke + 38
	12  libdispatch.dylib                   0x000000010d8b4e8e _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x000000010d8b63db _dispatch_once_callout + 66
	14  Niyo Global                         0x00000001088b57a0 +[FCTheme sharedInstance] + 97
	15  Niyo Global                         0x0000000108948d01 +[FCUtilities setNavigationPropertyForBar:] + 63
	16  Niyo Global                         0x000000010889d52b -[FCInterstitialViewController viewDidLoad] + 2041
	17  UIKitCore                           0x00007fff48c7598e -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] + 83
	18  UIKitCore                           0x00007fff48c7a8ac -[UIViewController loadViewIfRequired] + 1084
	19  UIKitCore                           0x00007fff48c7acc9 -[UIViewController view] + 27
	20  UIKitCore                           0x00007fff48beb8f5 -[UINavigationController preferredContentSize] + 187
	21  UIKitCore                           0x00007fff48b8f2c8 -[UIPresentationController preferredContentSizeDidChangeForChildContentContainer:] + 64
	22  UIKitCore                           0x00007fff48b8b10f __56-[UIPresentationController runTransitionForCurrentState]_block_invoke.465 + 178
	23  UIKitCore                           0x00007fff4932eb76 _runAfterCACommitDeferredBlocks + 352
	24  UIKitCore                           0x00007fff4931f304 _cleanUpAfterCAFlushAndRunDeferredBlocks + 248
	25  UIKitCore                           0x00007fff4934fb0d _afterCACommitHandler + 85
	26  CoreFoundation                      0x00007fff23da1087 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	27  CoreFoundation                      0x00007fff23d9bb3e __CFRunLoopDoObservers + 430
	28  CoreFoundation                      0x00007fff23d9c08a __CFRunLoopRun + 1226
	29  CoreFoundation                      0x00007fff23d9b8a4 CFRunLoopRunSpecific + 404
	30  GraphicsServices                    0x00007fff38c39bbe GSEventRunModal + 139
	31  UIKitCore                           0x00007fff49325968 UIApplicationMain + 1605
	32  Niyo Global                         0x000000010763531b main + 75
	33  libdyld.dylib                       0x00007fff520ce1fd start + 1
	34  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by vipulRajput** [comment]
@harish-kumarc @hemanth-sudarsan  can you guys help me please???

**Comment by harish-kumarc** [comment]
Hi @vipulRajput can you please clean your project, remove FreshchatSDK via commenting ```Pod FreshchatSDK``` in Podfile and after that uncomment ```Pod FreshchatSDK``` and call pod install again. Also please try out our [samples](https://github.com/freshworks/freshchat-ios/tree/master/Sample) here with your AppId and Appkey.

**Comment by vipulRajput** [comment]
@harish-kumarc I tried everything, it just not getting initialised properly.....
and I checked sample project already, thats working fine.

**Comment by vipulRajput** [comment]
@harish-kumarc its run time error, project is able to  build successfully...

**Comment by hemanth-sudarsan** [comment]
@vipulRajput 
Can you confirm whether you have this step under Build phases of your target.
<img width="813" alt="Screenshot 2021-02-10 at 12 19 00 PM" src="https://user-images.githubusercontent.com/45059530/107475581-5f1ffe80-6b9a-11eb-8c94-6be235c253aa.png">
If not then this issue will occur, you have to manually add these steps.

**Comment by hemanth-sudarsan** [comment]
@vipulRajput Closing this issue. If you still face this issue please reopen it.
