### ISSUE TITLE
Attributes cameraCaptureEnabled and gallerySelectionEnabled not working

### ISSUE THREAD

**Issue by TOrnelas** [freshworks/freshchat-ios#133]
## Describe the bug
Setting `gallerySelectionEnabled` and `cameraCaptureEnabled` on the initialisation does not show any UI for this on the chat view.

I'm initialising the SDK on `didFinishLaunchingWithOptions` as follows:

```
        let freshchatConfig: FreshchatConfig = FreshchatConfig.init(
            appID: "myId",
            andAppKey: "myKey"
        )
        freshchatConfig.domain = "myDomain"
        freshchatConfig.cameraCaptureEnabled = true
        freshchatConfig.gallerySelectionEnabled = true
        freshchatConfig.teamMemberInfoVisible = true
        freshchatConfig.showNotificationBanner = true
        freshchatConfig.responseExpectationVisible = true
        Freshchat.sharedInstance().initWith(freshchatConfig)
```

## Expected behavior
Some camera UI should be available on the chat UI, in order for the user to upload media.

## Platform
- [x] iOS

## Freshchat SDK version
- SDK version : 4.1.5

## Device information
- [x] is reproducible on all devices? 

```
 * Both on simulator
 * And real device
```

## Screenshot/ Video recording 
![image](https://user-images.githubusercontent.com/17816841/107130131-a2d8e680-68c2-11eb-9c8a-ab65383e4424.png)

**Comment by hemanth-sudarsan** [comment]
@TOrnelas 
If you have not added the following keys in your info.plist, it will not show the options.
Privacy - Camera Usage Description
Privacy - Photo Library Usage Description
You would have got the logs about the same in console.

**Comment by TOrnelas** [comment]
This fixed my issue. However, would be nice to mention this requirement on the documentation 👍
