### ISSUE TITLE
Oops No messages here when I open the app for the first time in IOS

### ISSUE THREAD

**Issue by Sathyan-Elangovan** [freshworks/freshchat-ios#134]
When I open the app for the first the time & try to open the fresh chat, it is showing "Oops! No messages here" screen. After that I closed the app & opened it again. If i open the fresh chat now, it is working, showing the chat screen. I couldn't find any issues here.But I don't why its not working while opening for the first time

**Comment by hemanth-sudarsan** [comment]
@Sathyan-Elangovan 
First time it wait for channels to fetch, so thats why you were seeing that message. But once channels are fetched, it will switch to channel list or messaging screen directly. Can you delete the app and check on first time by being there on the screen for sometime. It will switch automatically, if not switching please send the screenshot.

**Comment by Sathyan-Elangovan** [comment]
@hemanth-sudarsan 
Thanks.I will check that & update you

**Comment by Sathyan-Elangovan** [comment]
Hi @hemanth-sudarsan  I almost waited for 3 minutes on the same screen it is not switching to any screens .For your reference I am attaching the screen shots.
![2021-02-11-2](https://user-images.githubusercontent.com/61688116/107739010-e94c9c00-6d2d-11eb-915b-469bf1d3853b.jpeg)
![2021-02-11](https://user-images.githubusercontent.com/61688116/107739039-f7022180-6d2d-11eb-939a-d5a6095c8215.jpeg)

**Comment by hemanth-sudarsan** [comment]
@Sathyan-Elangovan May I know what is the SDK version being used?
Are you using JWT authentication inside SDK? Please also send your SDK code implementation to show conversation.
Send us your Freshchat domain, so we could check from our end.

**Comment by hemanth-sudarsan** [comment]
@Sathyan-Elangovan Closing this issue.
Please reopen if you face the issue.
