### ISSUE TITLE
Cordova Plugin is Outdated

### ISSUE THREAD

**Issue by ebofi** [freshworks/freshchat-ios#135]
Hi,

The so called Official recommendation for Cordova or Monaca apps, the plugin https://github.com/techaffinity/freshchat-phonegap is outdated and no longer maintained,  Due to recent Ios update on ukwebview etc, we cant use this branch anymore,

So we are asking that, is the Freshworks team does not understand the need of an official plugin release for hybrid apps,. since hybrid apps are changing the way we interact and develop and still Freshworks don't see it coming,... strange.

**Comment by hemanth-sudarsan** [comment]
@ebofi Updated the plugin check.
