### ISSUE TITLE
Keep asking for photo permission

### ISSUE THREAD

**Issue by asaturg** [freshworks/freshchat-ios#138]
## Describe the bug
When you allow access only to selected photos, on each app launch app asks for Photos permission  
## Steps to reproduce
   
1. Clean installed app with FreshChat SDK integrated
2. Open Conversation Screen.
3. Press on Attachment icon and select Upload from gallery
4. Choose Selected Photos on Permission popup, select any photo and close
5. Close and relaunch app
6. You will be asked for Photo permission every time you lunch app.

## Expected behavior
Should not ask for permission every time

## Platform
- iOS

## Freshchat SDK version
- SDK version : 4.1.8

## Device information
- reproducible on all devices

## Screenshot/ Video recording 
![image](https://user-images.githubusercontent.com/3206363/114727135-0104c880-9d4f-11eb-946e-7130264fb669.png)

**Comment by hemanth-sudarsan** [comment]
@asaturg Will look into this and update you.

**Comment by hemanth-sudarsan** [comment]
@asaturg You have to have this key PHPhotoLibraryPreventAutomaticLimitedAccessAlert in info.plist and it need to be set to YES.
