### ISSUE TITLE
Support for Apple Silicon (M1) iOS Simulator

### ISSUE THREAD

**Issue by T2SoftDev** [freshworks/freshchat-ios#139]
Trying to run iOS app with latest Freshchat SDK (4.1.8) using latest Xcode 12.5 in native (ARM) mode on Apple Silicon Mac (M1). Running app on iOS device works fine, but building for iOS Simulator causes the following linker error:

_ld: in /Users/Developer/Projects/App/libFDFreshchatSDK.a(FCCategoryViewOmniKBaseBehaviour.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/Developer/Projects/App/libFDFreshchatSDK.a' for architecture arm64_

Building for iOS Simulator using Xcode in emulation mode (Rosetta 2) solves build problem for Simulator, but causes performance degradation for Xcode & problems to running on iOS device.

As far as I know it is common problem for all third-party frameworks still built without support for new Apple architecture (arm64). Most frameworks already done this transition. Freshchat is the last framework in our app without this support. Please add arm64 support for your framework as soon as possible to let us use full power of new Macs without hustle switching Xcode between native ARM mode and Intel emulation with Rosetta 2! 🙏

**Comment by otaviocc** [comment]
Hi @harish-kumarc, @hemanth-sudarsan, I'm facing the same problem. Freshchat's the only 3rd-party dependency we depend on which doesn't support the architecture. Do you know if there's a fix on the way? Thanks!

**Comment by harish-kumarc** [comment]
We have informed our product team regarding this request.
You can reach out to us through support@freshchat.com for further queries.
