### ISSUE TITLE
APNs Auth Key Support

### ISSUE THREAD

**Issue by juanxme** [freshworks/freshchat-ios#28]
Please add support to APNs Auth Key

**Comment by MuthuFD** [comment]
@juanxme Thank for the request. 
We have not prioritised this yet. We will update you when the priority changes.

**Comment by iangmaia** [comment]
@MuthuFD Any updates on this?

**Comment by marcknock** [comment]
First of all, there really isn't a distinction between production and sandbox anymore for APNS, so your web UI should be updated if possible.

This issue is for supporting Apple's push notification keys. These keys do not expire like certificates.

Right now Freshchat has us uploading APNS certificates, which expire within a year or two.

Please allow us to upload .p8 keys which do not expire. These can be generated in the Apple development portal.

**Comment by marcknock** [comment]
This is still an issue a year on, please, this is a serious issue that needs to be resolved.

**Comment by T2SoftDev** [comment]
@hemanth-sudarsan, @harish-kumarc
Could you please comment on this? https://developer.apple.com/news/?id=c88acm2b

Finally, APNs Auth Key support would be awesome!

**Comment by hemanth-sudarsan** [comment]
@T2SoftDev This is  HTTP/2-based Apple Push Notification service (APNs). We are already supporting it.
If you have any feature requirements, reach out to support@freshchat.com

**Comment by marcknock** [comment]
We just need a way to upload a .p8 key so we don't have to **update our certificates every year**, please, this is basic. Comment on that.

**Comment by hemanth-sudarsan** [comment]
@marcknock 
Write to our product support team, support@freshchat.com.

**Comment by T2SoftDev** [comment]
@hemanth-sudarsan It's good to know that your backend is ready, but as @marcknock already said, we need standard straithforward support for APNs auth keys (*.p8) in Freshchat Admin panel instead of deprecated APNs push certificates (*.p12) which we should update every year!

**Comment by carman247** [comment]
Would also like support for APNs Auth Key instead of Auth Cert ... Please!

**Comment by harish-kumarc** [comment]
We have informed our product team regarding this request.
You can reach out to us through support@freshchat.com for further queries.
