### ISSUE TITLE
Have a way to disable app notification badge updates

### ISSUE THREAD

**Issue by iangmaia** [freshworks/freshchat-ios#61]
Now, once we forward the `UNUserNotificationCenterDelegate` callbacks to Freshchat, the SDK itself will update the app icon.
When you have your own updates (or NO updates), this can start to get messy, forcing the app to work around the SDK.
There should be an option in the SDK configuration, such as the other ones we have, to enable/disable application icon badge updates.

**Comment by harish-kumarc** [comment]
Thanks for the note @iangmaia, Will discuss more with team and surely update you on it.

**Comment by marcknock** [comment]
This is absolutely necessary, the SDK should never override `UIApplication.applicationIconBadgeNumber` without the app's permission to do so. The application badge number may be used for something else.

**Comment by SiSa68** [comment]
@harish-kumarc Also is there any way to disable notification permission request?

**Comment by harish-kumarc** [comment]
For badge update we are checking with team how this can be improved.
@SiSa68 The push permission prompt will comes if app has push capabilities and user hasn't enable push.
To disable inapp banner config flag can be set to false "config.showNotificationBanner =false". 
Just to disable all Freshchat only notification for your app, the workaround is to upload a valid certificate with different bundleId.

**Comment by Ganyev** [comment]
@harish-kumarc also faced with this inconvenience issue. Any news for it?

**Comment by harish-kumarc** [comment]
We have informed our product team regarding this request.
You can reach out to us through support@freshchat.com for further queries.
