### ISSUE TITLE
Calling unreadCountWithCompletion outside the main thread will trigger Core Data multithreading assertions

### ISSUE THREAD

**Issue by marcknock** [freshworks/freshchat-ios#81]
```
-(void)unreadCountWithCompletion:(void(^)(NSInteger count))completion;
```
Calling this method outside of the main thread will cause issues with your Core Data implementation. If you have concurrency assetions enabled in your target, you will see them pop up by calling this method in the background. **Either mark this method as needing to be called from the main thread in your documentation, or better, ensure MO and MOC thread safety**.

When developing and testing your SDK, please enable `-com.apple.CoreData.ConcurrencyDebug 1` in your launch arguments. Users may call your methods from arbitrary threads, and it is your responsibility to only touch your managed objects on the thread associated with the moc (see the `perform...` methods in `NSManagedObjectContext`, they are useful for ensuring thread safety).

Note: multi threading assertions are buggy on iOS 11.

See: 
* https://oleb.net/blog/2014/06/core-data-concurrency-debugging/
* https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/Concurrency.html

**Comment by hemanth-sudarsan** [comment]
@marcknock Fixed this issue. Thanks for letting us know about the issue.
