### ISSUE TITLE
Attaching pictures from iOS leads to rotated pictures on web app

### ISSUE THREAD

**Issue by marcknock** [freshworks/freshchat-ios#87]
Repro steps: attach a picture taken with your phone sideways.

Go to the Freshchat web interface, you will see the picture is not properly rotated. It should show as it shows on iOS.

This has to do that iOS embeds the rotation of an image in the EXIF Orientation tag, which is not honored by most web clients, assuming it is not stripped out by Freshchat when sent to your servers.

This needs to be fixed at some point in your iOS to web image pipeline, either honor at runtime in your web client, or burn in rotation by modifying the file at some point in the upload chain.

**Comment by kondratk** [comment]
Hi, 
we are experiencing the same problem at iOS SDK 4.1.3.

**Comment by harish-kumarc** [comment]
We have fixed the issue with release v6.6.2. Please update to latest version.
