### ISSUE TITLE
Allow us to present the support screen with a prefilled chat message

### ISSUE THREAD

**Issue by marcknock** [freshworks/freshchat-ios#90]
Often we want to pass an error message to be sent to the support team, please add a parameter to the method that shows the chat screen, so we can pass in a pre-filled message.

**Comment by hemanth-sudarsan** [comment]
@marcknock We have a sendMessage() function, which can be used before showing the chat screen. We also added user events tracker in the latest SDK v3.1.0, if you like to track error as separate event.

**Comment by marcknock** [comment]
We need it to be pre-filled, so the user can add more information as to what happened to cause that error. We don't want to be sending messages without the user's consent.

Intercom supports this feature.

**Comment by thidayatullah** [comment]
@hemanth-sudarsan 
`sendMessage()` function send the message automatically by the SDK and therefore takes over control from User.
I agree with @marcknock that we need the text to be pre-filled (and user can edit it) before sending it them self.

**Comment by harish-kumarc** [comment]
We have informed our product team regarding this request.
You can reach out to us through support@freshchat.com for further queries.
