### ISSUE TITLE
New Core Data Multithreading Violations

### ISSUE THREAD

**Issue by marcknock** [freshworks/freshchat-ios#95]
<img width="596" alt="Screen Shot 2020-02-21 at 4 15 48 PM" src="https://user-images.githubusercontent.com/43761071/75081815-80896580-54c5-11ea-8e6a-d1abbe7e69eb.png">

Please test your code with `-com.apple.CoreData.ConcurrencyDebug 1` on your scheme launch arguments. All Core Data apps should be run with this during development.

Proper thread containment is essential when dealing with managed objects and contexts.

I believe this specific error is new to recent releases of Freshchat.

See #81.

**Comment by harish-kumarc** [comment]
Thanks for the info @marcknock , we will check and analyse it form our side.

**Comment by hemanth-sudarsan** [comment]
@marcknock Fixed this issue. Thanks for letting us know about the issue.
